### ISSUE TITLE
UnboundLocalError: local variable 'inlist' referenced before assignment

### ISSUE THREAD

**Issue by MyraBaba** [lim-anggun/FgSegNet#1]
any idea?

Traceback (most recent call last):
  File "/Users/alpullu/Downloads/FgSegNet-master/FgSegNet/FgSegNet.py", line 372, in <module>
    results = generateData(train_dir, dataset_dir, scene)
  File "/Users/alpullu/Downloads/FgSegNet-master/FgSegNet/FgSegNet.py", line 242, in generateData
    del X_list_temp, inlist, gtlist
UnboundLocalError: local variable 'inlist' referenced before assignment

**Comment by lim-anggun** [comment]
hi,
Because of _FgSegNet.py_ couldn't find dataset dir. Make sure _FgSegNet.py_ points to the right path of your dataset. I updated paths in  _FgSegNet.py_ and Readme, maybe you can follow up.
